name: Kwiki-Notify-IRC
version: 0.01
abstract: announce updates to your Kwiki on IRC channels
author: Ian Langworth <langworth.com>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.32
  POE::Component::IKC::ClientLite: POE::Component::IRC
  YAML: Term::ANSIColor
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
